Listening for transport dt_socket at address: 5001
2019-03-04 00:54:42.562: DNA 启动...开始
2019-03-04 00:54:42.563: DNA 启动...java version "1.8.0_111"
2019-03-04 00:54:42.563: DNA 启动...Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
2019-03-04 00:54:42.563: DNA 启动...Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
2019-03-04 00:54:42.566: DNA 启动...应用ID：1B865CB4FBC7941AFF960D951CCFEBD8
2019-03-04 00:54:42.982: DNA 启动...注册JDBC驱动[MySQLDriver5]，驱动版本[5.1]
2019-03-04 00:54:43.098: DNA 启动...注册JDBC驱动[DB2Driver9]，驱动版本[3.1]
2019-03-04 00:54:43.200: DNA 启动...注册JDBC驱动[OracleDriver11]，驱动版本[11.1]
log4j:WARN No appenders could be found for logger (org.eclipse.jetty.util.log).
log4j:WARN Please initialize the log4j system properly.
2019-03-04 00:54:45.596: DNA 启动...实例化信息定义
2019-03-04 00:54:45.613: DNA 启动...装载多语言信息
2019-03-04 00:54:45.614: DNA 启动...准备启动站点
2019-03-04 00:54:45.614: DNA 启动...实例化表定义
2019-03-04 00:54:45.723: DNA 启动...确定表定义对其他元素的引用
2019-03-04 00:54:45.723: DNA 启动...实例化ORM定义
2019-03-04 00:54:45.747: DNA 启动...确定ORM定义对其他元素的引用
2019-03-04 00:54:45.747: DNA 启动...初始化ORM定义
2019-03-04 00:54:45.747: DNA 启动...实例化模型脚本引擎
2019-03-04 00:54:45.756: DNA 启动...初始化群集资源模式
2019-03-04 00:54:45.757: DNA 启动...实例化服务对象
2019-03-04 00:54:45.879: DNA 启动...注册服务调用器
2019-03-04 00:54:46.245: DNA 启动...确定资源定位信息
2019-03-04 00:54:46.246: DNA 启动...确定资源引用信息
2019-03-04 00:54:46.246: DNA 启动...初始化资源
2019-03-04 00:54:46.342: DNA 启动...半启用日志管理器
2019-03-04 00:54:46.342: DNA 启动...初始化服务
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2019-03-04 00:54:46.561: DNA 启动...启用日志管理器
2019-03-04 00:54:46.565: DNA 启动...站点启动完成
2019-03-04 00:54:46.565: DNA 启动...完毕
osgi> 三月 04, 2019 12:57:44 上午 org.apache.http.impl.execchain.RetryExec execute
信息: I/O exception (java.net.SocketException) caught when processing request to {}->http://ip.taobao.com:80: Connection reset
三月 04, 2019 12:57:44 上午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {}->http://ip.taobao.com:80
java.lang.InterruptedException
	at com.jiuqi.dna.core.impl.ContextImpl.checkValid(ContextImpl.java:3602)
	at com.jiuqi.dna.core.impl.ContextImpl.internalGetList(ContextImpl.java:1958)
	at com.jiuqi.dna.core.impl.ContextImpl.getList(ContextImpl.java:1449)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService.updateSystemNodeInfo(SystemNodeManageService.java:435)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService.access$1(SystemNodeManageService.java:379)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService$SyncServerInfoOnceTaskHandler.handle(SystemNodeManageService.java:311)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService$SyncServerInfoOnceTaskHandler.handle(SystemNodeManageService.java:1)
	at com.jiuqi.dna.core.resource.ResourceService$SimpleTaskMethodHandler.handle(ResourceService.java:1)
	at com.jiuqi.dna.core.impl.ServiceBase$TaskMethodHandler.handle(ServiceBase.java:1)
	at com.jiuqi.dna.core.impl.ContextImpl.serviceHandleTask(ContextImpl.java:349)
	at com.jiuqi.dna.core.impl.AsyncTaskImpl.workDoing(AsyncTaskImpl.java:146)
	at com.jiuqi.dna.core.spi.work.Work.doWork(Work.java:345)
	at com.jiuqi.dna.core.spi.work.WorkingThread.run(WorkingThread.java:44)
java.lang.InterruptedException
	at com.jiuqi.dna.core.impl.ContextImpl.checkValid(ContextImpl.java:3602)
	at com.jiuqi.dna.core.impl.ContextImpl.internalGetList(ContextImpl.java:1958)
	at com.jiuqi.dna.core.impl.ContextImpl.getList(ContextImpl.java:1449)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService.updateSystemNodeInfo(SystemNodeManageService.java:435)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService.access$1(SystemNodeManageService.java:379)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService$SyncServerInfoOnceTaskHandler.handle(SystemNodeManageService.java:311)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService$SyncServerInfoOnceTaskHandler.handle(SystemNodeManageService.java:1)
	at com.jiuqi.dna.core.resource.ResourceService$SimpleTaskMethodHandler.handle(ResourceService.java:1)
	at com.jiuqi.dna.core.impl.ServiceBase$TaskMethodHandler.handle(ServiceBase.java:1)
	at com.jiuqi.dna.core.impl.ContextImpl.serviceHandleTask(ContextImpl.java:349)
	at com.jiuqi.dna.core.impl.AsyncTaskImpl.workDoing(AsyncTaskImpl.java:146)
	at com.jiuqi.dna.core.spi.work.Work.doWork(Work.java:345)
	at com.jiuqi.dna.core.spi.work.WorkingThread.run(WorkingThread.java:44)
java.lang.InterruptedException
	at com.jiuqi.dna.core.impl.ContextImpl.checkValid(ContextImpl.java:3602)
	at com.jiuqi.dna.core.impl.ContextImpl.internalGetList(ContextImpl.java:1958)
	at com.jiuqi.dna.core.impl.ContextImpl.getList(ContextImpl.java:1449)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService.updateSystemNodeInfo(SystemNodeManageService.java:435)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService.access$1(SystemNodeManageService.java:379)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService$SyncServerInfoOnceTaskHandler.handle(SystemNodeManageService.java:311)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService$SyncServerInfoOnceTaskHandler.handle(SystemNodeManageService.java:1)
	at com.jiuqi.dna.core.resource.ResourceService$SimpleTaskMethodHandler.handle(ResourceService.java:1)
	at com.jiuqi.dna.core.impl.ServiceBase$TaskMethodHandler.handle(ServiceBase.java:1)
	at com.jiuqi.dna.core.impl.ContextImpl.serviceHandleTask(ContextImpl.java:349)
	at com.jiuqi.dna.core.impl.AsyncTaskImpl.workDoing(AsyncTaskImpl.java:146)
	at com.jiuqi.dna.core.spi.work.Work.doWork(Work.java:345)
	at com.jiuqi.dna.core.spi.work.WorkingThread.run(WorkingThread.java:44)
java.lang.InterruptedException
	at com.jiuqi.dna.core.impl.ContextImpl.checkValid(ContextImpl.java:3602)
	at com.jiuqi.dna.core.impl.ContextImpl.internalGetList(ContextImpl.java:1958)
	at com.jiuqi.dna.core.impl.ContextImpl.getList(ContextImpl.java:1449)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService.updateSystemNodeInfo(SystemNodeManageService.java:435)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService.access$1(SystemNodeManageService.java:379)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService$SyncServerInfoOnceTaskHandler.handle(SystemNodeManageService.java:311)
	at com.squarms.deploy.core.internal.service.SystemNodeManageService$SyncServerInfoOnceTaskHandler.handle(SystemNodeManageService.java:1)
	at com.jiuqi.dna.core.resource.ResourceService$SimpleTaskMethodHandler.handle(ResourceService.java:1)
	at com.jiuqi.dna.core.impl.ServiceBase$TaskMethodHandler.handle(ServiceBase.java:1)
	at com.jiuqi.dna.core.impl.ContextImpl.serviceHandleTask(ContextImpl.java:349)
	at com.jiuqi.dna.core.impl.AsyncTaskImpl.workDoing(AsyncTaskImpl.java:146)
	at com.jiuqi.dna.core.spi.work.Work.doWork(Work.java:345)
	at com.jiuqi.dna.core.spi.work.WorkingThread.run(WorkingThread.java:44)
三月 04, 2019 12:58:26 上午 org.apache.http.impl.execchain.RetryExec execute
信息: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://ip.taobao.com:80: The target server failed to respond
三月 04, 2019 12:58:26 上午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {}->http://ip.taobao.com:80
三月 04, 2019 12:59:45 上午 org.apache.http.impl.execchain.RetryExec execute
信息: I/O exception (java.net.SocketException) caught when processing request to {}->http://ip.taobao.com:80: Connection reset
三月 04, 2019 12:59:45 上午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {}->http://ip.taobao.com:80
三月 04, 2019 1:00:13 上午 org.apache.http.impl.execchain.RetryExec execute
信息: I/O exception (java.net.SocketException) caught when processing request to {}->http://ip.taobao.com:80: Connection reset
三月 04, 2019 1:00:13 上午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {}->http://ip.taobao.com:80
三月 04, 2019 1:01:13 上午 org.apache.http.impl.execchain.RetryExec execute
信息: I/O exception (java.net.SocketException) caught when processing request to {}->http://ip.taobao.com:80: Connection reset
三月 04, 2019 1:01:13 上午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {}->http://ip.taobao.com:80
